### ISSUE TITLE
completely broken with RKE2...

### ISSUE THREAD

**Issue by KyleSanderson** [rancher/local-path-provisioner#290] opened 2023-01-30 04:16 UTC
Kind of unclear what's going on here as there's reports going back saying there's issues with OpenShift and similar. Retail RKE2 install on 1.24. Making the "helper" pod privileged creates the path, but every other pod still can't use it.

**Comment by KyleSanderson** [comment] 2023-01-30 04:19
https://github.com/rancher/local-path-provisioner/issues/283
https://github.com/rancher/local-path-provisioner/issues/282

**Comment by derekbit** [comment] 2023-01-30 04:19
Did you try https://github.com/rancher/local-path-provisioner/issues/283#issuecomment-1356316957?

**Comment by derekbit** [comment] 2023-01-30 04:23
@KyleSanderson 
Can you provide your env information?

```
Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 
Number of management node in the cluster: 
Number of worker node in the cluster: 
Node config
OS type and version: 
SELinux enabled (true/false):
CPU per node: 
Memory per node: 
Disk type(e.g. SSD/NVMe):
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): 
```

**Comment by KyleSanderson** [comment] 2023-01-30 04:23
> Did you try [#283 (comment)](https://github.com/rancher/local-path-provisioner/issues/283#issuecomment-1356316957)?

Yes, no impact. This is very easy to reproduce...

**Comment by KyleSanderson** [comment] 2023-01-30 04:25
Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.24.10+rke2r1
Number of management node in the cluster: SINGLE NODE
OS type and version:  5.14.0-162.12.1.el9_1.0.1.x86_64
SELinux enabled (true/false): Enforcing
CPU per node: 92
Memory per node: 1024
Disk type(e.g. SSD/NVMe): NVMe
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Metal

**Comment by derekbit** [comment] 2023-01-30 04:27
> Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.24.10+rke2r1 Number of management node in the cluster: SINGLE NODE OS type and version: 5.14.0-162.12.1.el9_1.0.1.x86_64 SELinux enabled (true/false): Enforcing CPU per node: 92 Memory per node: 1024 Disk type(e.g. SSD/NVMe): NVMe Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Metal

I see. 
Will the helper pod work correctly if you disable the SELinux?
BTW, what's your OS distro (`uname -a`)?

**Comment by KyleSanderson** [comment] 2023-01-30 04:40
Confirmed, it's selinux. RHEL9.1 retail.

**Comment by derekbit** [comment] 2023-01-30 04:49
> Confirmed, it's selinux. RHEL9.1 retail.

Thanks for your information. I will investigate this issue.
It might be caused by the SELinux. You can disable the SELinux and check it can work. If yes, I can work on it with more confidence.

**Comment by KyleSanderson** [comment] 2023-01-30 04:52
Yes, it is working now, and I have a replaced filesystem underneath (where it continues to work). Just need those environment variables to make this usable from a "real deployment" perspective.
Every other user is going to encounter this on modern ELs.

**Comment by derekbit** [comment] 2023-02-14 12:09
@KyleSanderson 
Fixed in https://github.com/rancher/local-path-provisioner/pull/295. Will release 0.0.24 soon. Thank you.

**Closed by derekbit** 2023-02-14 12:10 UTC
Labels: Investigate

**Comment by KyleSanderson** [comment] 2023-02-14 15:13
Thank you. If the variables stuff could get some love https://github.com/rancher/local-path-provisioner/issues/291 that would be very appreciated. My NAS provider barely supports folder names longer than 30 characters.

**Comment by derekbit** [comment] 2023-02-14 15:23
> Thank you. If the variables stuff could get some love #291 that would be very appreciated. My NAS provider barely supports folder names longer than 30 characters.

Sure. Will check it. Thanks for the feedback.

**Comment by derekbit** [comment] 2023-02-14 17:15
> Thank you. If the variables stuff could get some love #291 that would be very appreciated. My NAS provider barely supports folder names longer than 30 characters.

The hindrance of the issue is related to the backward compatibility. Need to investigate more.
